server:
     port: 3000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwer1234
    url: jdbc:mysql://192.168.140.160:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
ignore:
    urls:
        - /authentication/**
        - /**/*.css
        - /social
        - /signin
        - /signup
        - /info
        - /health
        - /metrics/**
        - /loggers/**
        - /mobile/token
       
auth:
    loginPage: /authentication/require
    loginProcessingUrl: /authentication/form
